name: Publish

on:
  push:
    tags:
      - '*.*'

jobs:
  Build:
    permissions:
      contents: write
      id-token: write # 👈 Required for cosign OIDC
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get Environment Variables
        run: |
          $tag = "${{ github.ref }}" -replace 'refs/tags/', ''
          "tag=$tag" | Out-File -Append -FilePath $Env:GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Download Dalamud Latest
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Restore Nuget Packages
        run: dotnet restore AetherLink/AetherLink.csproj

      - name: Build Plugin
        run: dotnet build --no-restore -c Release AetherLink/AetherLink.csproj -p:AssemblyVersion=${{ env.tag }} -p:FileVersion=${{ env.tag }} -p:PackageVersion=${{ env.tag }} -p:InformationalVersion=${{ env.tag }} --output .\build

      - name: Zip Plugin
        run: Compress-Archive -Path .\build\* -DestinationPath .\build\AetherLink.zip

      - name: Install Cosign
        run: |
          curl -L https://github.com/sigstore/cosign/releases/latest/download/cosign-windows-amd64.exe -o cosign.exe

      - name: Sign Plugin Zip with Cosign
        run: |
          .\cosign.exe sign-blob --yes `
            --output-certificate build\AetherLink.zip.cert `
            --output-signature build\AetherLink.zip.sig `
            build\AetherLink.zip

      - name: Publish Plugin + Signature + Cert
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/AetherLink.zip
            ./build/AetherLink.zip.sig
            ./build/AetherLink.zip.cert
          token: ${{ secrets.GITHUB_TOKEN }}
